### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by aindilis** [paperswithcode/galai#14]
Hi,

I'm relatively new to all this.  I used conda to install.  Then I used this:

```
import galai as gal

model = gal.load_model(name = 'standard', num_gpus = 1)
model.generate("The Schwarzschild radius is defined as: \\[")
```

but I'm getting a:

torch.cuda.OutOfMemoryError: CUDA out of memory. 

I had assumed 6B parameters would fit into 24GB VRAM.

I've also tried: 

export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128'    

My questions are:

Is there any way to run the standard model on 24GB?

Is there any way to know ahead of time which models will fit into which GPUs without simply trying them out?  I don't see any memory requirements listed for this (or most other projects, as well).

Which model will fit into 24GB?

Thanks!
Andrew

p.s.

(galai) andrewdo@ai2:/var/lib/myfrdcsa/sandbox/galai-20221116/galai-20221116$ python frdcsa.py
Traceback (most recent call last):
  File "frdcsa.py", line 3, in <module>
    model = gal.load_model(name = 'standard', num_gpus = 1)
  File "/media/andrewdo/s3/sandbox-new/galai-20221116/galai-20221116/galai/__init__.py", line 41, in load_model
    model._load_checkpoint(checkpoint_path=get_checkpoint_path(name))
  File "/media/andrewdo/s3/sandbox-new/galai-20221116/galai-20221116/galai/model.py", line 63, in _load_checkpoint
    load_checkpoint_and_dispatch(
  File "/home/andrewdo/miniconda3/envs/galai/lib/python3.8/site-packages/accelerate/big_modeling.py", line 366, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/home/andrewdo/miniconda3/envs/galai/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 701, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param)
  File "/home/andrewdo/miniconda3/envs/galai/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 124, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 23.70 GiB total capacity; 21.54 GiB already allocated; 281.31 MiB free; 21.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by dcruiz01** [comment]
24GB VRAM is not going to be enough for the 6B parameter version ('standard') running at full precision (float32). However, you can try running the standard version at half precision via:
`model = gal.load_model(name = 'standard', num_gpus = 1, dtype = 'float16')`

If that doesn't work, then I'm afraid you'll be stuck with the base version (1.3B parameters) until GAL is available on HuggingFace with an int8 implementation. Hopefully that happens soon, because it will cut the required VRAM in half once again, more or less.

Good luck!

**Comment by aindilis** [comment]
@dcruiz01 Thank you so much, using float16 worked!
