### ISSUE TITLE
Can't install galai via pip

### ISSUE THREAD

**Issue by ANarayan** [paperswithcode/galai#2]
Hi! 

I tried installing galai in my conda environment (Python 3.8) via `pip install galai` but am seeing the following error:

```
Collecting galai
  Using cached galai-1.0.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jk9o1509/galai_8a2029a3d367447e9978185cff95291d/setup.py", line 16, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Thanks!

**Comment by SRDdev** [comment]
Facing `pip install galai` Issue

>C:\Users\LENOVO>pip install galai
Collecting galai
  Downloading galai-1.0.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-install-l5k9vdxp\galai_863740bada3146c6a82f2a14d31a2d3e\setup.py", line 16, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Similar to [ANarayan](https://github.com/ANarayan) problem

**Comment by aicrumb** [comment]
using 
```
pip install git+https://github.com/paperswithcode/galai
```
worked for me, if you need a temporary fix until the main package gets fixed (upgrading pip didn't work in my case)

**Comment by poldham** [comment]
This is a little different to @ANarayan but documenting to assist others coming to the thread with pip issues. 

On a Mac M1 I initially got an error installing for python 3.10 because of dependencies on py 3.8 which is likely to trip people up. The following then worked fine for me. 

conda create -n galactica python=3.8 
conda activate galactica 
pip install git+https://github.com/paperswithcode/galai

**Comment by khandriod** [comment]
@poldham I am running on the same environment but I am facing this error. 
```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Successfully built galai
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects
(galai) ➜  models

```

**Comment by khandriod** [comment]
The below commands should work fine:
```
conda create -n galia python=3.9
conda activate galia
pip install git+https://github.com/paperswithcode/galai
```

**Comment by FurkanGozukara** [comment]
> using
> 
> ```
> pip install git+https://github.com/paperswithcode/galai
> ```
> 
> worked for me, if you need a temporary fix until the main package gets fixed (upgrading pip didn't work in my case)

Thank you

**Comment by mkardas** [comment]
`pip install galai` should work since version 1.0.1. Please reopen if you still experience problems.
