### ISSUE TITLE
Galai not cleaning the downloaded zip files

### ISSUE THREAD

**Issue by Kaelorn** [paperswithcode/galai#20]
I just installed galai and started downloading the standard version on notebook.

Since each update of the progress bar creates a new line of log instead of refreshing the progress bar I stopped the download to start again on terminal.

The problem is when I try to download the model again it begins to download the second file... And if you interrupt again and try again to download the model it will crash with this error message: `PytorchStreamReader failed reading zip archive: failed finding central directory`

I am pretty sure the zip file it downloads are not cleared so it tries to unpack incomplete files and crashes because of that

Is there any way to delete the model files to download again?

**Comment by sangfrois** [comment]
I also stopped downloading one model file and got the same error when trying to re-download it. A manual way to delete the zip file would seem reasonable. How can I find the saving path ?

**Comment by brandonbiggs** [comment]
I've been exploring this as well. My local files are in `~/.cache/galactica/`. The comment in the code seems to be off. It indicates `~/.cache/galai/` but the code shows `~/.cache/galactica/` - https://github.com/paperswithcode/galai/blob/bef775fc8bccdd172e0bef69e77023de6cb35c5f/galai/utils.py#L121

**Comment by mkardas** [comment]
Hi all, in galai 1.1.0 we switched to transformers for checkpoints management. See the details at https://huggingface.co/docs/transformers/installation#cache-setup for information about where the cache is located and how to change it. Please reopen if you still have any issues.
