### ISSUE TITLE
Please list python package dependencies on README

### ISSUE THREAD

**Issue by rfernand2** [paperswithcode/galai#26]
The galai package seems to have some dependencies (PyTorch?  Tensorflow?).  Please list those in your install instructions on the README.

**Comment by rfernand2** [comment]
To clarify, does one need to install pytorch before installing galai?  I ran into an error about not having a CUDA DLL installed (Windows 11) when I didn't install pytorch.  When I did install pytorch and set num_gpus=N (in the load_model call), it worked correctly on Windows 11 and Ubuntu 20.

**Comment by Legor** [comment]
The dependencies are listed in the requirements.txt file.
You should install them with `pip install -r requirements.txt` first.
Besides that, it was easier for me to just use the huggingface API instead of the galai package.

**Comment by mkardas** [comment]
Hi @rfernand2, thanks for reporting. All the dependencies should be installed automatically when you install the package. If pytorch is not present or if it's older than 1.12, it is (re)installed. Depending on your platform it might happen that the pytorch version installed as a dependency won't have CUDA support. In that case please install it manually first, following the instructions at https://pytorch.org/get-started/locally/.
