### ISSUE TITLE
Why only part of the answer to the question is output？

### ISSUE THREAD

**Issue by ysj0930** [paperswithcode/galai#27]
>>> model.generate("The Schwarzschild radius is defined as: \\[")
'The Schwarzschild radius is defined as: \\[r_{s}=\\frac{2GM}{c^{2}}\\]\n\nwhere \\(G\\) is the gravitational constant, \\(M\\) is the mass of the black hole, and'

**Comment by RJT1990** [comment]
Thanks for the comment, use the `max_length` parameter.
