### ISSUE TITLE
Can be used on CPU?

### ISSUE THREAD

**Issue by SalvatoreRa** [paperswithcode/galai#28]
Hi, 

amazing works and very curious to try

can be used on a CPU (or parallelized on different CPUs)?

thank you,

Salvatore

**Comment by Tugees** [comment]
Hi Salvatore. Yes it is possible using the Hugging Face integration. The Readme has been uodated with the details.

**Comment by mkardas** [comment]
Hi @SalvatoreRa, as of galai version 1.1.0 you should be able to easily run the inference on CPU with `load_model(..., num_gpus=0)` (the default if there's no CUDA device). Please reopen if you still have any issues.
