### ISSUE TITLE
Figure 3 explanation

### ISSUE THREAD

**Issue by Muennighoff** [paperswithcode/galai#30]
Sorry, a few things are unclear to me about Fig 3:
1) What is generated by the model? Everything starting from `<work>`? Including Answer?
2) Is it zero-shot like in the image?
3) Is it a mistake from the model that it generates « & >?
4) Does the model literally predict the output of the program (0.0051) or did you run the program externally and then add it to the image?

Thanks 🤗

<img width="820" alt="Screenshot 2022-11-19 at 14 56 03" src="https://user-images.githubusercontent.com/62820084/202847260-ad696bac-65aa-4b18-907c-849fcd2b5681.png">

**Comment by RJT1990** [comment]
Thanks for the comment: for inference, it generates everything after <work> including Answer. It is "zero-shot" in the sense you just need to prompt with <work> at test-time.

**Comment by Muennighoff** [comment]
Interesting, so the calculation 0.0051 was not done using an external program, but the model did it itself!
Thanks 👍
