### ISSUE TITLE
How to continue text generation?

### ISSUE THREAD

**Issue by hwasiti** [paperswithcode/galai#31]
After the first text generation, how would one continue to generate more?

**Comment by Piyushsinganjude** [comment]
Okay thanks

**Comment by RJT1990** [comment]
hey, change the max_length parameter

**Comment by yratof** [comment]
Where is the max_length param?

**Comment by mkardas** [comment]
`model.generate` and `model.generate_reference`. There's both `max_new_tokens` and `max_length`. You can run `help(model.generate)` for more info or check https://github.com/paperswithcode/galai/blob/bf126df3e6cce16b0a893b4d3b0ad0e3ce8a6492/notebooks/Introduction%20to%20Galactica%20Models.ipynb for usage example.
