### ISSUE TITLE
How to set the correct view of bibliographic references?

### ISSUE THREAD

**Issue by kmarz84** [paperswithcode/galai#42]
How to display correct (full) references to literary sources in the text? Now it looks something like this: _"...This has been mainly driven by the increase in the use of animal models for preclinical research [[START_REF] Animal models in translational medicine: Validation and prediction, Denayer[END_REF]]. ..."_

**Comment by mkardas** [comment]
The model generates all references in the `[START_REF] Title, First author[END_REF]` form. To get the bibliographic data you can query an external service based on the title and author generated by the model. See f.e., https://github.com/sckott/habanero .
