### ISSUE TITLE
Keyerror when load galactica-30b 

### ISSUE THREAD

**Issue by BruceStayHungry** [paperswithcode/galai#47]
Great work!  When I load galactica-30b, it shows `KeyError: 'decoder.layers.34.final_layer_norm.bias'`

I have downloaded the model into my disk. The key error occurred when running the following code:
```
model_path = "local-model-path"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = OPTForCausalLM.from_pretrained(model_path, device_map="auto",  torch_dtype=torch.float16)
```
Thanks for any help!

**Comment by mkardas** [comment]
Hi @BruceStayHungry, we fixed the 30B checkpoint. Can you check if it works now?
