### ISSUE TITLE
Why is CUDA is required for pytorch?

### ISSUE THREAD

**Issue by blair0011** [paperswithcode/galai#49]
Please remove the CUDA requirement or export the model in a device agnostic format like ONNX. Some people just want to try out your models but their systems may not have a compatible Nvidia GPU.

**Comment by mkardas** [comment]
Hi @blair0011, can you check with galai version 1.1.0? You can load the model to RAM with `load_model(..., num_gpus=0)`.

**Comment by Pepe-Marquez** [comment]
Hi @mkardas, I could perfectly load the 'mini' setting `num_gpud=0`. Thanks

**Comment by blair0011** [comment]
I found the issue it was because WSL needed an update and conversion of my VM to version 2. Now everything works. Thanks
