### ISSUE TITLE
ValueError: The current `device_map` had weights offloaded to the disk. 

### ISSUE THREAD

**Issue by gitfans5** [paperswithcode/galai#57]
How to fix "ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format."? when running "model = gal.load_model("standard")"? Thanks.

**Comment by mkardas** [comment]
It looks like the model cannot fit into the RAM + VRAM. What is the amount of free RAM & VRAM? You can reduce memory requirement by using float16 inference with `load_model(..., dtype=torch.float16)`.
