### ISSUE TITLE
Files sizes of models

### ISSUE THREAD

**Issue by yratof** [paperswithcode/galai#60]
When running and fetching the models, what final file sizes can we expect from each of the available models?

Hugging face shows 9gb for the huge file, but running after PIP, the downloading hasn't stopped for an hour, it just keeps fetching ~9gb files

**Comment by yratof** [comment]
https://huggingface.co/facebook/galactica-120b/tree/main

~260gb

**Comment by mkardas** [comment]
Hi @yratof, I just pushed a jupyter notebook (https://github.com/paperswithcode/galai/blob/bf126df3e6cce16b0a893b4d3b0ad0e3ce8a6492/notebooks/Introduction%20to%20Galactica%20Models.ipynb) describing the details, see the Disk Space Requirements Section. In short, each model requires 2x the number of params:

![image](https://user-images.githubusercontent.com/13535078/207846378-b6aa2915-6d4c-488e-8f66-04e50dbc67c4.png)

~9 GB shown on the HuggingFace hub is just one of 26 shards.

**Comment by yratof** [comment]
> 

Perfect, I was looking at the standard model originally - I just need to run HUGE on a different SSD. C drive didn't like it so much :D
