### ISSUE TITLE
How to remove models

### ISSUE THREAD

**Issue by yratof** [paperswithcode/galai#61]
I wanted to test huge, but i ran it on the wrong drive, can't seem to see where the files are stored - is there a method of removing models?

**Comment by yratof** [comment]
Answer: `/home/username/.cache/huggingface/hub/model_name`

**Comment by mkardas** [comment]
Yes, see https://huggingface.co/docs/transformers/v4.25.1/en/installation#cache-setup for more details and other operating systems. You can change the download location by setting `TRANSFORMERS_CACHE` environment variable accordingly.
