### ISSUE TITLE
Could not find a version that satisfies the requirement promptsource

### ISSUE THREAD

**Issue by wladerer** [paperswithcode/galai#8]
Specifications:
Linux / pop!_os
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Python 3.10.6

Issue encountered when installing from repo
pip install git+https://github.com/paperswithcode/galai

ERROR: Could not find a version that satisfies the requirement promptsource (from galai) (from versions: none)
ERROR: No matching distribution found for promptsource

Might be associated with the following issue: https://github.com/bigscience-workshop/promptsource/issues/728
**Issue resolved when using Python 3.7**

**Comment by khatvangi** [comment]
I also got the same problem

**Comment by tmgthb** [comment]
I attempted to install promptsource manually and it gave exact same error with Python 3.10 version (as here with the Galatica). The promtsource library refers to need using the prior versions of Python. The installation worked without issue in a Cloud environment with the prior Python version for me without need to modify the setup.py file to exclude the version limitation.

**Comment by alibeyram** [comment]
Use python 3.9. 
That fixed the issue for me

**Comment by mkardas** [comment]
Hi @wladerer, can you check galai version 1.1.0? It should work with python 3.10.

**Comment by tmgthb** [comment]
Hi @mkardas I know the issue is closed, but to confirm I re-tested locally and the model runs now with Python 3.10 without need to update any code. Thank you for the fix.
